# Generated by Django 3.0.6 on 2020-09-05 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='employee_job',
        ),
        migrations.AddField(
            model_name='employee',
            name='employee_job',
            field=models.ManyToManyField(blank=True, to='employees.Availablejobs'),
        ),
    ]
